### ISSUE TITLE
The road to v0.18

### ISSUE THREAD

**Issue by josemarluedke** [josemarluedke/frontile#289]
We have been working on version 0.18 alpha/beta builds for a few months now. The new version includes major changes in styling and some breaking changes in components, as well as many new components. Below are a few things I would like to see completed before releasing the next major version. We will release 0.18 stable with the legacy forms and changeset-from pkg, but they will be dropped on 0.19.

**New features**
- [x] Input
    - [x] loading state, natively?
    - [x] Clear button #288
    - [x] Start and End content #282
- [x] Select
    - [x]  Loading state #339
    - [x]  Ability to render content for the selected item #512 
    - [x]  Filter/search #339
        - [x]  no results message
        - [x]  optional filter function
    - [x]  ability to use Native Select in forms pkg
    - [x]  Multiple with chips #509
    - [x]  Clear button #290
    - [x]  Selected item should be scrolled into view #339
    - [x] Focus Ring #339
    - [x] Dropdown size -> auto #339
    - [x] Test helpers to select, clear and others. 
- [x] Button
    - [x] Loading state #68
    - [x] onClick / onPress argument #373 #372
- [x] Listbox
    - [x] Groups / Sections
    - [x] Sub menu #558 
    - [x] Focus Ring
- [x] Modal / Drawer / Overlay
  - [x] Make animation is executed when rendering modal initially open #571

  
**Refactors**
- [x] Portals
    - [x] Try to remove the need for renderInElement (specifically in tests)
- [x] Move class fields to new object for style-variants
- [x] Move away from appearance and intent arguments -> variant & color, matches most UI libraries #577 #579
- [x] Add data-part & data-component attributes to all components #574

**Docs**
- [x] New Forms pkg
- [x] Deprecate ChangesetForm PKG
- [x] Rework
    - [x] Drawer
    - [x] Modal
    - [x] Overlay
    - [x] Notifications
- [x] Docs issue in Popover Focus Trapping
- [x] Document style slots
- [x] Theming (#328)
- [x] Customizing styles of components (#329)
- [x] How to keep docs for older Frontile versions? 

**Other issues**
- [x] Add config to disable overlay animations globally #219

New components 
- [x] Accordion #557
- [x] Filter (autocomplete) on Select
- [x] Avatar #346
- [x] Alert #555
- [x] Tabs #545
- [x] Pagination #565
- [x] External Link #564
- [x] Skeleton
- [x] Input OTP #537
- [x] Calendar (to be used in date picker) #568 
- [x] Date picker #578 
- [x] Switch #342
- [x] Tooltip #559 
- [x] Spinner (loading) #281

New components are nice to have, but most of them are not required.

**Comment by josemarluedke** [comment]
Closing as v0.18.0 is now released.
